package chronocache.core.parser;

public enum PlSqlTypes {
	SELECTED_ELEMENT,
	WHERE_CLAUSE,
	GROUP_BY_CLAUSE,
	EXPLICIT_JOIN,
	RELATIONAL_EXPRESSION,
	ATOM,
	CONSTANT,
	REGULAR_ID,
	NUMERIC,
	ID_EXPRESSION,
	HAVING_CLAUSE,
	STANDARD_FUNCTION,
	VALUES_CLAUSE,
	JOIN_ON_PART,
	GENERAL_ELEMENT,
	UNARY_EXPRESSION,
	QSH_IGNORE,
	TABLE_VIEW_NAME,
	QUOTED_STRING,
	ALIAS,
	LIMIT,
	ORDER_BY,
	ORDER_BY_ELEMENTS,
	SELECT
};
